Team-BrewBuds/BE_REPO

records/views.py, tests/like_tests.py
> #7 
> 댓글에 좋아요, 좋아요 취소 기능 구현 
close #12
=> 7 댓글 좋아요 기능

repo/profiles/managers.py, repo/profiles/models.py, repo/profiles/urls.py, repo/profiles/views.py, tests/conftest.py, tests/relationship_tests.py
> ex) #21 
- 팔로우/언팔로우 요청을 처리하는 API
- 기능 검증을 위한 테스트 코드 추가
close #21
=> 21 팔로우, 언팔로우 기능 

repo/profiles/serializers.py, repo/profiles/views.py
- 프로필 편집에서 많은 편집이 일어날것 같지 않아 patch 매서드만 사용
- 사용자 인증 적용
- 트랜잭션 적용
=> feat : 프로필 편집 기능

repo/beans/schemas.py, repo/beans/views.py, repo/profiles/schemas.py, repo/profiles/views.py, repo/records/schemas.py, repo/records/views.py
> #67 
drf_spectacular를 사용하여 API 문서를 작성하는 스키마 클래스를 정의하고 뷰에 적용하여 리펙토링 진행
스키마 정의
- beans, profiles, records 앱 내 'schemas.py'에 스키마 정의
뷰 리팩토링
- 기존 view에 작성한 인라인 스키마 정의 제거
- 새롭게 생성한 스키마 클래스 참조하도록 변경
이번 리팩토링을 통해 뷰의 가독성이 향상되었고, 스키마 정의를 별도로 관리할 수 있게 되어 코드 유지 보수가 용이해졌습니다.
=> 67 spectacular 데코레이터

repo/profiles/schemas.py, repo/profiles/views.py
> #20 
- spectacular 문서 수정( category 및 응답 예시 추가)
- 테스트 용도로 무작위 유저 20명 버디 추천 응답
- 추후 롤백 예정
=> 버디 추천 테스트용 데이터, api 수정

repo/profiles/schemas.py, repo/profiles/serializers.py, repo/profiles/views.py
> #20
API 응답 처리 개선, 추천 사용자에 대한 쿼리 최적화, 적절한 사용자 인증 보장
* 인증되지 않은 사용자에 대한 `401` 응답 설명이 `BudyRecommendSchema` 클래스에 추가되었습니다. (`repo/profiles/schemas.py`)
* 직렬화기가 중첩 관계를 보다 효과적으로 처리할 수 있도록 `BudyRecommendSerializer`의 `user` 필드를 `source=“*”` 매개 변수를 사용하도록 수정했습니다. (`repo/profiles/serializers.py`)
* 팔로워 수에 `annotate`를 사용하고 중복 코드를 제거하는 등, 추천 사용자 가져오기 쿼리를 최적화하기 위해 `BudyRecommendAPIView`를 업데이트했습니다. (`repo/profiles/views.py`)
* 사용자가 인증되지 않은 경우 `401` 오류를 반환하도록 `BudyRecommendAPIView`에 확인을 추가했습니다. (`repo/profiles/views.py`)
* 쿼리 최적화를 지원하기 위해 `repo/profiles/views.py`에서 `models`에 대한 가져오기를 추가했습니다. (`repo/profiles/views.py`)
=> 20 버디 추천 비회원

repo/profiles/schemas.py, repo/profiles/views.py, repo/records/services.py, repo/records/tasted_record/serializers.py
> #59 
- 정렬 옵션 업데이트,
- '좋아요' 개수를 포함하도록 쿼리 수정
- 새 필드를 포함하도록 시리얼라이저 업데이트 
- 쿼리 최적화
=> 59 프로필 시음기록 리스트 좋아요 정렬

repo/common/bucket.py, repo/common/serializers.py, repo/profiles/views.py, repo/records/models.py, repo/records/schemas.py, repo/records/services.py, repo/records/urls.py, repo/records/views.py, tests/profiles/profile_note_post_tests.py
> #25 #82 
> 사진 처리 향상, 오류 처리 개선, 페이지 매김 간소화를 위해 여러 파일에 걸쳐 여러 가지 변경 사항이 포함되어 있습니다. 
주요 변경 사항으로는 사진 업로드 및 관리 업데이트, 오류 처리 개선, 페이지 매김 간소화 등이 있습니다.
* 크기 유효성 검사 및 상세 응답으로 사진 업로드를 처리하는 `PhotoField`와 새로운 직렬화기(`PhotoDetailSerializer`, `PhotoUploadSerializer`, `PhotoUpdateSerializer`)가 추가되었습니다. (`repo/common/serializers.py`)
* 동적 업로드 경로 대신 정적 업로드 경로 형식을 사용하도록 `사진` 모델을 수정했습니다. (`repo/records/models.py`)
* 유효성 검사 및 오류 처리를 개선하여 사진 업로드, 업데이트, 삭제를 처리하도록 `PhotoApiView`를 업데이트했습니다. (`repo/records/views.py`)
* 'delete_photos' 함수의 오류 처리를 개선하여 특정 오류 메시지를 제공하고 실패 시 변경 사항을 롤백합니다. (`repo/common/bucket.py`)
* get_post_or_tasted_record_detail` 함수에 `object_type`에 대한 유효성 검사를 추가하여 잘못된 유형에 대해 `ValueError`를 발생시키도록 했습니다. (`repo/records/services.py`)
* 도우미 함수 `get_paginated_response_with_class`를 사용하여 …
=> 25 aws bucket meta data

config/settings/_base.py, config/settings/dev.py, config/settings/prod.py, config/settings/settings_modules/auth.py, config/settings/settings_modules/cors.py, config/settings/settings_modules/jwt.py, config/settings/settings_modules/social_auth.py, config/settings/settings_modules/spectacular.py, config/urls.py, poetry.lock, pyproject.toml
> #86 
- 개발환경 디버깅 툴 세팅
- settings 파일 모듈 분리
주요 변경 사항은 다음과 같습니다:
* [`config/settings/_base.py`](diffhunk://#diff-e4b24ecd88f07dcb980a9aa849e1eb25c1f64a86c582e593b03795f795750fcaL77-L178): 더 나은 정리를 위해 다양한 설정을 제거하고 별도의 모듈로 이동했습니다. [[1]](diffhunk://#diff-e4b24ecd88f07dcb980a9aa849e1eb25c1f64a86c582e593b03795f795750fcaL77-L178) [[2]](diffhunk://#diff-e4b24ecd88f07dcb980a9aa849e1eb25c1f64a86c582e593b03795f795750fcaL195-R106)
* [`config/settings/settings_modules/auth.py`](diffhunk://#diff-8241605f43eea972ab6e44c719cfd0744c15bf02c6babfd5041e75ed7ab3ab0cR1-R34): 인증 관련 설정을 위한 새 모듈을 생성했습니다.
* [`config/settings/settings_modules/cors.py`](diffhunk://#diff-bedf9a517e1d0da095b26f3c8f42855c17d3c0772d32775f5bdbb1780c45bc3eR1-R9): CORS 설정을 위한 새 모듈을 생성했습니다.
* …
=> 86 setting dev debug

config/settings/_base.py, repo/common/middleware/performance.py
> ex) #86 
'PerformanceMiddleware' 클래스 추가, 미들웨어 설정 업데이트, 로깅 설정
- django 서버 로그, 성능 로그 출력 설정
- django-debug-toolbar 요청 로그 제외 필터링 추가
- app.log 파일을 자동으로 생성하여 로깅하도록 설정
- DEBUG 필터링 설정으로 로깅 출력 환경 구분
- PerformanceMiddleware
- 메서드, 경로, 기간, 데이터베이스 쿼리 수 및 응답 상태를 포함한 요청 성능 세부 정보를 기록
=> feat : 로깅 설정

repo/interactions/report/models.py, repo/interactions/report/schemas.py, repo/interactions/report/serializers.py, repo/interactions/report/services.py, repo/interactions/report/urls.py, repo/interactions/report/views.py, repo/interactions/urls.py, repo/records/models.py, repo/records/schemas.py, repo/records/serializers.py, repo/records/urls.py, repo/records/views.py, tests/factorys.py, tests/interactions/report_tests.py
> #91 #92 #99 
- **모델 추가**: `Report` 모델을 생성하여 신고 정보를 저장합니다. 신고자는 작성자, 객체 타입, 객체 ID, 신고 사유, 상태, 생성일 등의 정보를 포함합니다.
- **직렬화 및 검증**: `ReportSerializer`를 추가하여 신고 데이터의 직렬화와 검증을 처리합니다.
- **서비스 클래스**: `ReportService` 클래스는 신고를 생성하고, 기존 신고를 확인하며, 관련된 작성자를 조회하는 기능을 제공합니다.
- **스키마 정의**: `ReportSchema`를 정의하여 API 문서화 및 검증을 담당합니다.
- **뷰 추가**: `ReportAPIView`를 추가하여 신고 생성 요청을 처리합니다. 이 뷰는 `ReportService`와 `ReportSerializer`를 사용합니다.
- `repo/interactions/report/urls.py`에 신고 API 엔드포인트를 위한 URL 패턴을 추가하고, 이를 `repo/interactions/urls.py`에서 기존 URL 패턴에 포함시켰습니다.
- 기존 `repo/records` 모듈에서 사용되던 `Report` 모델, 직렬화기, 스키마, 뷰, URL 등을 제거했습니다. 이는 새로운 신고 시스템이 적용되었기 때문입니다.
- 새로운 신고 기능에 맞춰 기존 테스트를 수정하고, 신고 데이터의 검증과 에러 처리가 제대로 이루어지는지 확인하는 테스트를 추가했습니다.
이 변경 사항은 전체적으로 신고 기능을 새로운 방식으로 재구성하고, 불필요한 구형 기능은 제거하는 작업을 포함합니다.
=> 99 interaction report service

repo/interactions/like/schemas.py, repo/interactions/like/services.py, repo/interactions/like/urls.py, repo/interactions/like/views.py, repo/interactions/urls.py, repo/records/schemas.py, repo/records/services.py, repo/records/urls.py, repo/records/views.py, tests/interactions/like_tests.py
> #91 #92 #99 
이 풀 리퀘스트는 `repo/interactions` 모듈에 새로운 “좋아요” 기능을 구현합니다. 변경 사항에는 게시물, 맛보기 레코드 및 댓글의 '좋아요' 처리를 위한 스키마, 서비스, 보기 및 테스트 추가가 포함됩니다. 또한 기존 코드를 리팩터링하여 새 기능을 원활하게 통합합니다.
주요 변경 사항은 다음과 같습니다:
* [`repo/interactions/like/schemas.py`](diffhunk://#diff-55b986c20751d8d11d553b7ebc9ba895966ec656484e10ed8edac5b6c9ffaaf7R1-R76): 좋아요 기능에 대한 OpenAPI 문서를 처리하기 위해 `like_post_schema` 및 `like_delete_schema`와 함께 `LikeSchema` 클래스를 추가했습니다.
* [`repo/interactions/like/services.py`](diffhunk://#diff-620d9ed8344fc8e69f828fe87e00880e9d083dc178ec6d4aa23f0741ed870823R1-R53): 좋아요를 늘리고, 줄이고, 확인하는 메서드 등 좋아요에 대한 비즈니스 로직을 관리하는 `좋아요서비스` 클래스를 도입했습니다.
* [`repo/interactions/like/views.py`](diffhunk://#diff-139ab74118bb7ae9fe5b2a57a9a27e1c67a1f6970d9daa311f5e2deae6e3dc3dR1-R23): LikeService` 클래스를 사용하여 좋아요에 대한 POST 및 …
=> 99 interaction like service

repo/beans/services.py, repo/interactions/note/services.py, repo/interactions/relationship/services.py, repo/interactions/report/services.py, repo/profiles/services.py
> #92 
- 리포지토리 속성 사용을 Django 모델의 기본 `객체` 메니저 대한 직접 호출로 대체
- profile, bean, note, report, relationship Service
=> 97 profiles 유저 도메인 서비스 로직 분리 및 수정

repo/profiles/services.py, repo/profiles/validators.py
- 커피 생활 데이터 수정 로직 변경
- patch /profiles/ : 변경하고자 하는 커피 생활 요소 요청시 수정  
- 닉네임 공백 설정 불가 버그 수정
=> 프로필 정보 수정 로직 변경

repo/profiles/urls.py, repo/profiles/views.py
> #120 
> 로그인 수정 - nickname 존재 여부 추가
=> feat: 로그인 - 닉네임 여부 추가

repo/profiles/urls.py, repo/profiles/views.py
Reverts Team-BrewBuds/BE_REPO#121
=> Revert "feat: 로그인 - 닉네임 여부 추가"

repo/profiles/urls.py, repo/profiles/views.py
=> 120 로그인 수정

repo/profiles/urls.py, repo/profiles/views.py
=> 132 로그인 수정

config/settings/_base.py, poetry.lock, pyproject.toml, repo/beans/admin.py, repo/common/admin_filters.py, repo/common/admin_mixins.py, repo/interactions/admin.py, repo/profiles/admin.py, repo/profiles/models.py, repo/records/admin.py, repo/records/models.py
> 
> 관리자 인터페이스의 필터링 및 표시 기능을 개선
- [django-admin-rangefilter](https://pypi.org/project/django-admin-rangefilter/) 라이브러리 추가
- 다양한 모델에 대한 사용자 정의 필터 추가 (`NumericRangeFilter`, `DateRangeFilter` 등)
- 공통 관리자 기능을 위한 믹스인 구현 (`CreatedAtMixin`, `AuthorMixin` 등)
- `@admin.register` 데코레이터를 사용한 관리자 클래스 등록 개선
- 관리자 인터페이스의 표시 및 필터링 옵션 향상
=> Admin 기능 추가

poetry.lock, pyproject.toml, repo/common/utils.py, repo/interactions/report/admin_services.py, repo/interactions/report/urls.py, repo/interactions/report/views.py
> #141 
> 사용자 활동 보고서 exel 파일 다운로드 API 
- pandas, openpyxl 라이브러리 추가 및 사용 
- report 앱에 엔드포인트 추가
=> Admin report api

repo/profiles/views.py
=> feat: 애플 로그인 수정

repo/profiles/models.py, repo/profiles/schemas.py, repo/profiles/urls.py, repo/profiles/views.py
> ex) #158 
> 계정정보 조회 API
> 계정탈퇴(삭제) API
=> 158 계정정보 계정탈퇴

docker/prod.Dockerfile, poetry.lock, pyproject.toml
=> feat: poetry 수정

docker/prod.Dockerfile
=> feat: dockerfile scikit-learn 수정

docker/prod.Dockerfile
=> feat: dockerfile for sckit-learn install

docker/prod.Dockerfile
=> feat: dockerfile scikit-learn

docker/prod.Dockerfile
=> feat: dependency install

poetry.lock, pyproject.toml
=> feat: scikit-learn 버전 다운

config/settings/_base.py
=> feat: blacklist 관련 설정 추가

repo/profiles/serializers.py, repo/profiles/views.py
=> 193 활동요약 수정

.env.example, config/settings/prod.py, config/settings/settings_modules/sentry.py, poetry.lock, pyproject.toml
=> Set sentry monitering

repo/profiles/schemas.py, repo/profiles/serializers.py, repo/profiles/views.py
>
> 원두 추천시 작성한 시음기록 3개 이하일때 공식원두 필터링 추가 
> view에서 추천 로직 service 레이어로 분리
=> 원두 추천 로직 수정
